version: '3.8'

services:
  db:
    container_name: sscm
    image: mysql:latest
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: sscm
      MYSQL_USER: sungkihwan
      MYSQL_PASSWORD: Sungkihwan1!
      MYSQL_ROOT_PASSWORD: kihwan
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

